### ISSUE TITLE
conflict in REST API url paths in function-manager

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#102]
- [X] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description

the url path of getRuns is /v1/function/runs now, 
it will be conflicted with /v1/function/{functionName} when there's a function called "runs", it may not happen but indeed a potential bugs.

## Possible Implementation

change the url path of getRuns to something like /v1/runs or /v1/functionruns or whatever won't cause the conflict.

## Complexity

- [X ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [X] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
This needs to be fixed.  In fact I would like the API to be changed to /v1/runs which is consistent.  Query args can be used for filters.
