### ISSUE TITLE
ambiguity in function manager handler names: getFunctionRuns and getRuns

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#103]
- [ ] Bug
- [ ] Feature
- [X] Enhancement

## Detailed Description

there're there handlers in function manager: 
getFunctionRuns,
getRuns,
getRun

their functions and required parameters are ambiguous, in fact:
getFunctionRuns --> get function runs by function name AND optionally run id
getRuns --> get all functions runs 
getRun --> get function run only by run id

It might be ok, but when it comes to dipatch cli get_runs.go there're
getFunctionRun --> get runs by function name AND run id
getFunctionRuns --> get runs by function name
getRuns --> get all runs 
which I cannot really tell the functions of them without carefully look into the code. 

## Possible Implementation

I suggest to they should renamed to something better reflect their real functions 
e.g. 
getRunsByFunctionName
getRuns
getRun

or maybe combine getRuns and getFunctionRuns if possible

## Complexity

- [X] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [X] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
I think we could probably just get by with "getRuns" and "getRun", with everything else just being a filter on getRuns.  I agree that the current handlers are ambiguous.
