### ISSUE TITLE
Add support for Clojure (and possibly other JVM languages)

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#121]
- [ ] Bug
- [x] Feature
- [ ] Enhancement

## Detailed Description
Support for running JVM-based functions (starting with Clojure)

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by imikushin** [comment]
Thank you for this @kars7e :)

I'm taking it

**Comment by kars7e** [comment]
Correct me if I'm wrong @rjew @imikushin but this is done!

**Comment by imikushin** [comment]
Yep, this is done: https://github.com/dispatchframework/clojure-base-image
