### ISSUE TITLE
CLI shell completion

### ISSUE THREAD

**Issue by imikushin** [vmware/dispatch#122]
It'd be nice to have shell (bash and zsh) tab-completion for dispatch CLI. 

- [ ] Bug
- [ ] Feature
- [x] Enhancement

## Detailed Description
CLI users would be able to hit TAB to complete or see possible completions (if there are several) of the current word in their CLI command. 

## Context
Typing commands will get easier and require less viewing of `--help`. This allows quicker (and cooler) demos and provides a more enjoyable user experience. 

## Complexity
- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

**Comment by seanhuxy** [comment]
It's cool, I am also interested in having this feature.

**Comment by embano1** [comment]
Ah, I see where the issue is (thought cobra would have it out of the box)
https://github.com/spf13/cobra/issues/107
