### ISSUE TITLE
Services don't need to listen on HTTPS

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#149]
The ingress controller terminates TLS so, the services themselves don't need to listen on HTTPS or have certs configured.

- [ ] Bug
- [ ] Feature
- [x] Enhancement

## Detailed Description

We should simplify as much as we can, and since the ingress -> service communication is over unencrypted HTTP, there is no sense in listening on HTTPS and requiring certs to run a service.  This is particularly important during development where one may just be spinning up a service in isolation.

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Fixed by #557
