### ISSUE TITLE
create entities twice --> internal server error

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#166]
```
$ ../dispatch-darwin create secret blog-webapp-secret secret.json
Created secret: 6f823382-53a2-4635-8843-e3c0207bc7d6
$ ../dispatch-darwin create secret blog-webapp-secret secret.json
[Code: 500] create Secret error: internal server error when creating the secret
```
It will be create if the error message tells the secret already exists instead of a internal server error
This might only limit to secret apis.

- [X] Bug
- [ ] Feature
- [ ] Enhancement

## Complexity

- [X] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [X] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
This is already fixed:
```
➜  dispatch create secret vcenter ~/work/dispatch/secrets/vcenter.json
Created secret: vcenter
➜  dispatch create secret vcenter ~/work/dispatch/secrets/vcenter.json
[Code: 409] Conflict: error creating secret: non-unique name
```
