### ISSUE TITLE
cannot inject secret when using api-gateway

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#171]
users are not able to take advantage of api-gateway and secret at the same time, as 
- there's no way to dynamically inject secret when invoke functions from api-gateway.
- static secret injection while creating functions is not support

- [ ] Bug
- [X] Feature
- [ ] Enhancement

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [X] High - Blocker

I think it's quite a blocker, a non-trivial application/function with high possibility need secrets and apis 

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
As a workaround, could the function be defined with the secret?

**Comment by seanhuxy** [comment]
thanks @berndtj . Close this issue as it's already addressed
