### ISSUE TITLE
unfriendly message when create a function with an existing name

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#183]
if there's already an function named post in dispatch, creating another prints out an internal error message, which is not helpful for outsiders to debug
```
$ dispatch create function blog-webapp-image post post.js --secret blog-webapp-secret 
[Code: 500] Error: internal server error when storing a new function

$ dispatch delete function post
Deleted function: post

$ dispatch create function blog-webapp-image post post.js --secret blog-webapp-secret 
Created function: post
```

- [X] Bug
- [ ] Feature
- [ ] Enhancement

## Complexity

- [X] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [X] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
As of `0.1.16+`, creating a function with an existing name will result in:
`[Code: 409] Conflict: error creating function: non-unique name`
