### ISSUE TITLE
Use source dir when creating functions

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#19]
As a function developer I'd like to have all the function related files (source code, dependencies, schemas, README, metadata, etc) placed in the function source directory. 

A possible CLI command to deploy a function would look like:
```bash
$ vs create function ./my-func
```

**Comment by imikushin** [comment]
Closing for now: we're going to see how far we can go with a single source file per function. 

We're adding system and runtime dependencies when creating images, so functions can be relatively high level and (we think) should fit into a single file.
