### ISSUE TITLE
Generic Code 400 error creating images (following examples)

### ISSUE THREAD

**Issue by embano1** [vmware/dispatch#201]
- [ ] Bug
- [ ] Feature
- [x] Enhancement

## Detailed Description
Bootstrapping the Dispatch environment and then following the vcenter example throws the following error message when creating the images:

`$ [Code: 400] Bad request: store error when adding base image`

This is of course due to the already present images (created during bootstrapping). Needs a doc fix.

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
This is fixed
