### ISSUE TITLE
Slack vCenter example - Secret associated with subscription isn't populated in context

### ISSUE THREAD

**Issue by embano1** [vmware/dispatch#202]
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description
Slack vCenter example - Secret associated with subscription isn't populated in context. Result: Function is run, but webhook is not called. 

Discussed with @tenczar 

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
AFAIK this is fixed now, please reopen if reoccurs
