### ISSUE TITLE
Dispatch uninstall doesn't remove the docker-registry from helm

### ISSUE THREAD

**Issue by tenczar** [vmware/dispatch#205]
- [ ] Bug
- [ ] Feature
- [x] Enhancement

## Detailed Description

Using the `dispatch uninstall` command fails to remove the new internal docker registry from helm.

## Context

Dispatch uninstall should remove all components installed by Dispatch

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit): v0.1.6
* Dispatch Chart version (or image[s] tag):
* Operating System and version: macOS
* Kubernetes version (and distribution): v1.8.1
* Etc (any other useful environmental information):

**Comment by neosab** [comment]
I will get this fixed

**Comment by markpeek** [comment]
Might be good to add a test of 1. install, 2. uninstall, 3. verify no services are left running.

**Comment by neosab** [comment]
#284 addresses this
