### ISSUE TITLE
READM.md structure not really clear for first time user

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#206]
It is an issue that I have with a set of first time users during the hackathon Tuesday.

If they haven't install minikube previously, the quick start direct them to go to the "Standard Installation" -- "minikube" section, which is fine. But some of them, after installing minikube, spontaneously continue to install helm, configure oauth app and so on. 

We'd better not confuse users with an all-included README, where people get lost by so many links.

Suggest: **use the readme as general introductions and an index to different sections** (e.g. quick start, standard installation, instructions on installing dependencies like minikube, FAQ, Troubleshooting, appendix), where those sections can be organized by https://vmware.github.io/dispatch/  

- [ ] Bug
- [ ] Feature
- [X] Enhancement

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [X] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Fixed via #207
