### ISSUE TITLE
Architecture diagram shows etcd as config store

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#208]
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description
The [architecture diagram](https://github.com/vmware/dispatch/blob/1b847738af6549ba1f6e2dae81f0d076b4b26e82/docs/images/dispatch-v1-architecture.png) still shows etcd as config store. Diagram should be updated to reflect the fact we're using Postgres now.

**Comment by berndtj** [comment]
Fixed in PR #207

**Comment by kars7e** [comment]
@berndtj I think you meant to close #206 not #207
