### ISSUE TITLE
Track test coverage in build

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#221]
Test coverage is not tracked, and we need to know where we stand.  Currently the build runs a coverage script, but the results are not stored anywhere.  We need to store and track the coverage.

- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Possible Implementation

This could be built into our dashboard.  And the results of the coverage could be posted by CI to the dashboard application.

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by zimengyang** [comment]
Initial tracking test coverage done by #230. Also add a new ci pipeline for sending test coverage when a merge in branch master happens.
