### ISSUE TITLE
Inconsistent usage of config file vs command line arguments in dispatch services

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#234]
Each service seems to choose an arbitrary combination of command line arguments and config file arguments.  This is confusing and needs to be standardized.

- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description

The function manager defines the following command line arguments:
```
	Config        string `long:"config" description:"Path to Config file" default:"./config.dev.json"`
	DbFile        string `long:"db-file" description:"Backend DB URL/Path" default:"./db.bolt"`
	DbBackend     string `long:"db-backend" description:"Backend DB Name" default:"boltdb"`
	DbUser        string `long:"db-username" description:"Backend DB Username" default:"dispatch"`
	DbPassword    string `long:"db-password" description:"Backend DB Password" default:"dispatch"`
	DbDatabase    string `long:"db-database" description:"Backend DB Name" default:"dispatch"`
	OrgID         string `long:"organization" description:"(temporary) Static organization id" default:"dispatch"`
	ImageManager  string `long:"image-manager" description:"Image manager endpoint" default:"localhost:8002"`
	SecretStore   string `long:"secret-store" description:"Secret store endpoint" default:"localhost:8003"`
	Faas          string `long:"faas" description:"FaaS implementation" default:"openfaas"`
	TemplatesPath string `long:"templates" description:"Path to function templates directory" default:"images/function-manager/templates"`
	ResyncPeriod  int    `long:"resync-period" description:"The time period (in seconds) to sync with FaaS" default:"10"`
	K8sConfig     string `long:"kubeconfig" description:"Path to kubernetes config file" default:""`
```
It also defines the following config file properties:
```
Openwhisk struct {
		AuthToken string `json:"auth_token"`
		Host      string `json:"host"`
	} `json:"openwhisk"`
	OpenFaas struct {
		Gateway string `json:"gateway"`
	} `json:"openfaas"`
	Riff struct {
		Gateway       string `json:"gateway"`
		K8sConfig     string `json:"k8s_config"`
		FuncNamespace string `json:"func_namespace"`
	} `json:"riff"`
	Registry struct {
		RegistryURI  string `json:"uri"`
		RegistryAuth string `json:"auth"`
	} `json:"registry"`
```

## Context

Developers need a consistent set of rules with regards to service configuration.

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Fixed via #557
