### ISSUE TITLE
Release "ingress" does not exist in minikube deployment -- install fails

### ISSUE THREAD

**Issue by ericstoekl** [vmware/dispatch#241]
- [X] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description

Installing dispatch fails when installing on minikube

```
$ dispatch install --file config.yml
Creating new certificate for domain 192.168.99.100
Updating certificate in namespace dispatch
Creating new certificate for domain 192.168.99.100
Updating certificate in namespace kong
Installing nginx-ingress helm chart
Error installing nginx-ingress chart: Release "ingress" does not exist. Installing it now.
Error: release ingress failed: clusterroles.rbac.authorization.k8s.io "ingress-nginx-ingress" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["ingresses/status"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:tiller 8855933c-179b-11e8-a8b3-080027801c5c [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
: exit status 1

```

## Context

Trying to get started with Dispatch. Do you need to install on a managed platform like GKE?

Here are the contents of my `config.yml`:

```
$ cat config.yml 
apiGateway:
  host: 192.168.99.100
dispatch:
  host: 192.168.99.100
  debug: true
  skipAuth: true
```

## Complexity

- [X] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [X] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
How do you get the version of the Dispatch CLI? `--help` doesn't show it, and there is no `dispatch version`
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
Ubuntu 1604
* Kubernetes version (and distribution):
Minikube 1.9.0
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Hey @ericstoekl, I'm seeing following error: `clusterroles.rbac.authorization.k8s.io "cluster-admin" not found`. You might have provisioned `minikube` without using `kubeadm`. In that case, you won't have RBAC role `cluster-admin`. You might want to re-run minikube with `--bootstrapper=kubeadm` to fix that. I included similar note in [PR to OpenFaaS](https://github.com/openfaas/faas-netes/pull/139).

However, we should take some steps to help people identify this issue themselves. another option would be to use something like [helm-local](https://github.com/adamreese/helm-local) or [including tiller libraries] in `dispatch install`.

**Comment by kars7e** [comment]
@ericstoekl did you have a chance to try again with my comments above? Let me know if it worked for you and if I can close the issue. Thanks!

**Comment by kars7e** [comment]
Closing this issue for now, if you hit the problem again, please reopen!
