### ISSUE TITLE
CLI support for Policies

### ISSUE THREAD

**Issue by neosab** [vmware/dispatch#265]
Implement CLI support for creating/deleting/listing policies. 

- [ ] Bug
- [X] Feature
- [ ] Enhancement

## Detailed Description

The user should be able to specify the rules for policies as command line flags. 

e.g dispatch create policy --name my-new-policy --rule user@example.com,function,* --rule user2@example.com,image,get
## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [X] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by zimengyang** [comment]
Create/delete/get/list/update supports added in #292 and #305.
