### ISSUE TITLE
Add a Bootstrap CLI Command 

### ISSUE THREAD

**Issue by neosab** [vmware/dispatch#267]
Add a bootstrap CLI command to enable/disable boostrap mode in dispatch.  Currently, we do this using the install command.

- [ ] Bug
- [X] Feature
- [ ] Enhancement

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [X] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by neosab** [comment]
It will be nice to have a separate `dispatch manage` command that can be enhanced for many day-2 operations. 

`dispatch manage bootstrap-mode --enable --user xyz@example.com`
`dispatch manage bootstrap-mode --disable`

On the implementation side, there are multiple options:-
1. This could target just the `dispatch-identity-manager` deployment using kubectl and enable/disable the args.
2. Leverage helm tags to target this change to just the identity-manager subchart.

**Comment by zimengyang** [comment]
closes via #375
