### ISSUE TITLE
Decouple language support from FaaS drivers

### ISSUE THREAD

**Issue by imikushin** [vmware/dispatch#269]
Add riff support for all languages currently supported by openfaas driver. 

- [ ] Bug
- [x] Feature
- [ ] Enhancement

## Context

We need to provide the same level of support for Riff and OpenFaaS. #256 is related. 

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

**Comment by imikushin** [comment]
Adding language support could be trivial if FaaS-specific function adapter only needed to use one interface to call function implementations. All language-specific runtime code could be packaged in a single docker image. 


# Problem

Currently, it’s hard to add support for new languages to Dispatch: 

1. To add a new language, it should be added to all FaaSs currently supported in a FaaS-specific way. 
2. To add a support for a new FaaS to Dispatch, one not only needs to implement the FaaS driver, but also add the languages in a FaaS-specific way. As a consequence, language support differs between FaaS-drivers.
3. It’s impossible to add a language without rebuilding Dispatch.


# Proposed solution

Base-image should include everything required to support a language, including:

- The language runtime and its standard library — usually installed as a system package
- Function adapter — a simple HTTP server implementing Function Runtime API (see below)
- Dockerfile template to build the function image

At function image building phase, function-manager would extract the template files from the base-image and render them using the function source code and metadata. The resulting Dockerfile are used to build the function image. 


## Function Runtime HTTP API

It’s a low level function invocation API typically implemented by a simple HTTP server written in the language we’re building the base image for. This API is called by the FaaS driver (through the FaaS engine) at function invocation time: 

- OpenFaaS would call it through its faas-netes proxy
- Riff would call it through the function-sidecar

Endpoint: /

**Request**
Method: POST
Headers:

- Content-Type: application/json
- Accept: application/json

Body:

- context
- payload

**Response**
Headers:

- Content-Type: application/json

Body:

- context
  - error — error object/value, null if no error occured
  - logs — array of log strings from the function run
- payload


## Required changes

**Base Images**

1. Add the Function Runtime HTTP API server.
2. Add function image Dockerfile template. 

**Function-manager**

1. Remove built-in FaaS- and language-specific function image templates.
2. Extract function image templates from the base-image.

**Comment by berndtj** [comment]
Are you implying that both riff and openfaas have the same HTTP payload?  Where is the FaaS specific code?  Do we still have FaaS specific templates, but they are all packaged in with the base images?  Can we make this into a spec, as the GitHub issue will get lost, and I think we need more detail.

**Comment by imikushin** [comment]
Openfaas and riff function containers are different but serve the same purpose: to run a function. The proposed design makes it possible to provide one implementation of the Function Runtime API per language and then use it from all FaaS drivers. 

Currently, FaaS specific code (the function wrapper) has to be implemented M×N times: for M drivers and N languages. 

In the proposed design it is divided in 2 separate parts: 
- the client - FaaS specific
- the server - language specific

As a result of the proposed change, we won't need FaaS specific templates: the result of rendering such templates is always going to be the same for the same FaaS. This part is going to become the responsibility of the FaaS driver.
