### ISSUE TITLE
Updating function returns error.

### ISSUE THREAD

**Issue by angel-ivanov** [vmware/dispatch#299]
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description
I've created function, and I wanted to modify the code in it. Sending PUT request on the function URL with the changes I've made results in error with status code 500. Here is the request body I am sending:
`{
    "code": "def handle(ctx, payload):\n    name = \"Noooone\"\n    place = \"Nowhere\"\n    if payload:\n        name = payload.get(\"name\", name)\n        place = payload.get(\"place\", place)\n    return {\"myField\": \"Hello, %s from %s\" % (name, place)}",
    "createdTime": -62167174767,
    "id": "91db142a-9fa8-4c72-a969-7e7539c6e47b",
    "image": "python3",
    "name": "python-exampleff808081620ab48b01620ab4a0590000",
    "schema": {
        "in": null,
        "out": null
    },
    "secrets": null,
    "status": "READY",
    "tags": null
}`
Body was initially taken from GET request on the function URL, and slightly modified the code property.

Response body:
`{
    "code": 500,
    "message": "internal server error when updating a FaaS function"
}`

**Comment by berndtj** [comment]
I am unaware of any current issues with regards to function update. Closing.
