### ISSUE TITLE
Update functionality missing from CLI and many API endpoints

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#33]
All entities should be updatable, and should be manageable through the CLI.

**Comment by berndtj** [comment]
Please open and track sub-issues.  Let's create issues for each command type (i.e. base-image, image, function, etc).  Also, include work on the server side as needed.

**Comment by tenczar** [comment]
I can't see a good way of creating sub issues. Should I just make sure to reference this issue in all of the 'sub-issues'? I think that would at least create a link from the comments here to each of those issues.

**Comment by berndtj** [comment]
Just edit the top comment with a list which refers to the related issues.  There is no official sub-issue support in GitHub.
