### ISSUE TITLE
Policy CLI Improvements

### ISSUE THREAD

**Issue by neosab** [vmware/dispatch#333]
Some improvements to the Policy CLI

- [X] Bug
- [ ] Feature
- [X] Enhancement

## Detailed Description

1. I am unable to create a policy using my email id. I get this error message 
```
dispatch create policy my-admin --subject "xyz@example.com" --action "get,create,update,delete" --resource "image,function,base-image,secret,iam,runs"
[Code: 605] Add Policy error: subjects.0 in body should match '^[\w\d\-]+$'
```
We should allow email id's in the regex.

2. I should be able to specify `*` in either **--action** or **--resources**. The API does allow this.

```
dispatch create policy my-admin --subject xyz@example.com --action "*" --resource "*"
[Code: 606] Add Policy error: actions.0 in body should be one of [get create update delete]
```

3. [Nice to have] If we can pretty print the rules in the policies, that will be easier to read
```
smurugesan-a01:dispatch smurugesan$ dispatch get policy my-admin
    NAME   |         CREATED DATE          |                                                                         RULES
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  my-admin | Fri Dec 31 16:53:43 LMT -0001 | [{"actions":["get","create","update","delete"],"resources":["image","function","base-image","secret","iam","runs"],"subjects":["xyzexamplecom"]}]
```

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by zimengyang** [comment]
#334 merged, working on the third issue
