### ISSUE TITLE
Using secrets might be tricky (debugging function input)

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#34]
I've defined a secret `slack`, which had single `slack_url` key with value. Then in the code, I defined:
```javascript
 let completeWebhook = context.secrets["slack_url"];
```

I've got successful execution (no error was thrown), although `completeWebhook` was empty.

The proper line should be: 
```javascript
 let completeWebhook = context.secrets["slack"].slack_url;
```

But this wasn't obvious. In normal, local development one could throw a bunch of debugging statements, but this gets tricky when executing via FaaS.

What would be useful is to have an example of input. After declaring a function, have something like:
```
vs exec function FUNCTION_NAME --debug 
```
Which would execute a function but would print the detailed input passed to the function by FaaS.

**Comment by berndtj** [comment]
Ultimately anything we respond with needs to come from the "run" data.  Currently, this looks like:

```
$ dispatch exec i-have-a-secret --wait --input '{"useless": "value"}' --json --secret open-sesame
{
    "blocking": true,
    "executedTime": 1515017045,
    "finishedTime": 1515017046,
    "functionId": "1f131335-b7aa-4d42-9842-394f2f87ebeb",
    "functionName": "i-have-a-secret",
    "input": {
        "useless": "value"
    },
    "logs": null,
    "name": "f0d84ea1-f7ff-408b-98ae-db6a2bedf4da",
    "output": {
        "message": "I know nothing"
    },
    "reason": null,
    "secrets": [
        "open-sesame"
    ],
    "status": "READY"
}
```

While this doesn't match the "context" object which is passed into the function exactly, it's close.  I'm not sure what do with the secret data, as I think printing it out if we just add the --debug flag is a security hole.  The CLI could also pretty easily construct the full "context" by combining the "run" with the "secrets".  Does this help?

**Comment by kars7e** [comment]
I believe that issue was opened before we had the ability to print run payload (and list it later on). Also, the secrets are less confusing now due to #77, So I'm ok with closing it for now
