### ISSUE TITLE
Java language support

### ISSUE THREAD

**Issue by imikushin** [vmware/dispatch#359]
Base image for Dispatch providing support for the Java language. The base image sources are going to be in this repo: https://github.com/dispatchframework/java-base-image

- [ ] Bug
- [x] Feature
- [ ] Enhancement

## Detailed Description

To add Java language support, Dispatch users will have to create a base-image with Java support in their Dispatch installation. 

### Function programming model
A function in Java will be a class implementing `java.util.function.BiFunction<T,U,R>` interface. T, U and R are type parameters and should be represented by JSON-encodable types:

- T — context, best represented by Map<String,Object>
- U — payload, can be any JSON-encodable value type
- R — output payload, can be any JSON-encodable value type

Hello.java:
```java
    package com.example.functions;
    
    import java.util.Map;
    import java.util.function.BiFunction;
    
    public class Hello implements BiFunction<Map<String, Object>, Map<String, Object>, String> {
        public String apply(Map<String, Object> context, Map<String, Object> payload) {
            final Object name = payload.getOrDefault("name", "Someone");
            final Object place = payload.getOrDefault("place", "Somewhere");
            
            return String.format("Hello, %s from %s!", name, place);
        }
    }
```

## Context

Dispatch users will use the Java base-image to create images and functions:

```
$ dispatch create base-image java-base vmware/dispatch-java-base:0.0.1

$ dispatch create image my-java-libs java-base --runtime-deps ./hello-proj/pom.xml

$ dispatch create function my-java-libs hello1-java \
  ./hello-proj/src/java/com/example/functions/Hello.java
```

## Possible Implementation

The function-server in the base image can be implemented using e.g. [Undertow](https://github.com/undertow-io/undertow) as HTTP server. 

Function image Dockerfile should contain steps to build the Java class from the provided source file and install it into the local filesystem Maven repo in the function image.

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [x] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
Will java support require more than one function file?  Unlike other languages, java requires on file per class.  I guess we can use private functions?

**Comment by imikushin** [comment]
Well, you can have no more than one **public** class per file: 

```java
package com.example.multiple;

public class PublicClass {
    PrivateImpl impl = new PrivateImpl();
}

class PrivateImpl {
    int implementationData;
}
```
is valid Java. Let's see how far we can stretch this "one file per function" idea :)

We do need to think of some way of providing libraries besides fetching them from artifact repos though: to be discussed in separate issues.
