### ISSUE TITLE
Need to refer to the secrets via secret name in addition to the key associated with the value.

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#38]
When secrets are defined, they are given a name.  That name then becomes the key in the "secrets" payload injected into the function.  This seemed like a good implementation at first, but it prevents you from naming keys "dev" and "prod" and using them interchangeably, for instance.

We need to decouple the name from the key/values.  This will of course require a way to resolve conflicts when the same key is defined in multiple secrets.

**Comment by berndtj** [comment]
@tenczar is this issue still open?
