### ISSUE TITLE
Deleting secret that does not exist produces a 500 error

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#380]
dispatch delete secret blah
received unexpected error: [DELETE /{secretName}][500] deleteSecret default  &{Code:500 Message:0xc420430080}

The above command should not return a 500 error.  It should return a 404.  We should never return 500 errors unless something goes wrong on our end.

- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Context

This is an issue in the service manager because it makes calls to the secret manager through the client API.  It cannot handle a 500 error, but should just skip a 404.

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by markpeek** [comment]
Dup of #182

**Comment by kars7e** [comment]
Closing as it's a duplicate
