### ISSUE TITLE
Use (real) persistent storage for "production" deployments

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#39]
Bolt DB only really works on a single host installation.  In a multi-node kubernetes environment, if pods are rescheduled upon restart, the database is lost.  This leads to very inconsistent state.

Either use etcd or consul.

**Comment by berndtj** [comment]
We are looking at using Postgres for the config DB as it's already a requirement for KONG.

**Comment by seanhuxy** [comment]
this issue should be addressed partially by PR https://github.com/vmware/dispatch/pull/78 however, current Postgres is not actually persistent. In the next step, we should probably use k8s PVC to persistently back it into disk.

**Comment by berndtj** [comment]
Let's close this issue, as we can now instruct "production" use-cases to deploy to an existing or external to dispatch postgres.  Persistent postgres is kind of out of our scope.  We just need to ensure that we can support an external postures via install

**Comment by seanhuxy** [comment]
sounds good to me, then I will close this issue, as it is addressed by https://github.com/vmware/dispatch/pull/78
