### ISSUE TITLE
Add dispatch apply command

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#394]
- [x] Bug
- [x] Feature
- [ ] Enhancement

## Detailed Description
When using a file with dispatch objects specified, it's currently not possible to process that file if some of the objects already exist, and some do not. `dispatch create -f` will fail with an error that some objects already exists, `dispatch update -f` will fail with an error that some objects do not exist. We need a command that is able to just create missing objects or update existing ones if they differ, ideally `dispatch apply` to align with kubernetes style.
## Context
When using a seed file, I've run:
```
$ dispatch create -f examples/seed.yaml
Created BaseImage: nodejs6-base
Created BaseImage: python3-base
Created BaseImage: powershell-base
Created Image: nodejs6
Created Image: python3
Created Image: powershell
Error when reading content of python3/hello.py: open python3/hello.py: no such file or directory
```
I was in the wrong directory. So I changed the directory, and I've run `create` again:
```
$ dispatch create -f seed.yaml
[Code: 409] Conflict: error creating base image: non-unique name
```
Ok, let's try using `update`:
```
$ dispatch update -f seed.yaml
Created BaseImage: nodejs6-base
Created BaseImage: python3-base
Created BaseImage: powershell-base
Created Image: nodejs6
Created Image: python3
Created Image: powershell
[Code: 404] Function not found: hello-py
```
It didn't work as well. We need a command that will ensure the state in dispatch to be equal to the file passed to it, similar to `kubectl apply`.

## Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

**Comment by tenczar** [comment]
oops. I should have read the description more thoroughly. this makes sense to me.
