### ISSUE TITLE
Deleting image with same name as base image deletes both.

### ISSUE THREAD

**Issue by tenczar** [vmware/dispatch#401]
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description

Create a base image called python3
```dispatch create base-image python3 dispatchframework/python3-base:0.0.0```
Create an image called python3
``` dispatch create image python3 python3```

I can successfully create a function using the image python3 and run it. When I delete the python3 image it deletes both the image and the base image.
```dispatch delete image python3```
This will delete both the image and the base image.

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
This is fixed by #504
