### ISSUE TITLE
Function error not displayed

### ISSUE THREAD

**Issue by rjew** [vmware/dispatch#403]
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description

When an error occurs when running a function, the error is returned as part of the context but we don't display this to the user. It would be nice to display the error that occurred and set the function run status as "ERROR".

Currently when a function throws an exception,
```
def handle(ctx, payload):
    raise Exception("oh no!")
```

A traceback is returned in the stderr, but the function still reports as "READY" and reason is `null`
```
$ dispatch exec fail --wait
{
    "blocking": true,
    "executedTime": 1524863021,
    "faasId": "00bbecbe-9815-44ce-8445-56715a107c6f",
    "finishedTime": 1524863021,
    "functionId": "65f708fd-61b9-4949-af1d-fba822d3abea",
    "functionName": "fail",
    "input": {},
    "logs": {
        "stderr": [
            "Traceback (most recent call last):",
            "  File \"main.py\", line 43, in exec_function",
            "    r = handler.handle(msg['context'], msg['payload'])",
            "  File \"/function-server/function/handler.py\", line 2, in handle",
            "    raise Exception(\"oh no!\")",
            "Exception: oh no!"
        ],
        "stdout": null
    },
    "name": "19f2a8ae-6010-4ad5-98f5-5cd611f09101",
    "reason": null,
    "secrets": [],
    "services": null,
    "status": "READY",
    "tags": []
}
```

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by imikushin** [comment]
Related to #356

**Comment by berndtj** [comment]
@rjew Is this done?

**Comment by rjew** [comment]
Not done yet. Working on it as part of the bigger error handling change.
