### ISSUE TITLE
Creation of invalid python function sometimes completes with status READY

### ISSUE THREAD

**Issue by rageorgiev** [vmware/dispatch#418]
## Bug Report
I have test that is trying to create Python function with invalid python code. Invalid python code is just a random characters i.e. not a python code at all. Not sure about the other runtimes (nodejs and etc).

### Expected behavior
Status of the function creation should always be reported as  'ERROR'.

### Current behavior
Most of the times function creation finishes with a proper status code of 'ERROR'. However it appears that sometimes after reporting the function status as INITIALIZED it moves to 'READY' state. 

### Steps to reproduce
1. Try to create python function with some invalid python code (some characters that can not be considered python code at all.)
2. Retry to create the invalid function several times.
3. Most of the times the status is reported properly as ERROR by sometimes the function status is reported as READY.

### Impact

High - Blocker - READY state should 100% mean function is ready to run.

**Comment by rjew** [comment]
Fixed by dispatchframework/python3-base-image#11
