### ISSUE TITLE
Transport does not obey "single namespace" option

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#430]
## Bug Report
Deployed dispatch with single namespace option:
```
dispatch install -f cascade-install.yaml --single-namespace default
```

Transport still installed in "dispatch" namespace:
```
helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART               	NAMESPACE
api-gateway	1       	Fri May 11 10:19:40 2018	DEPLOYED	kong-0.1.2          	default  
dispatch   	1       	Fri May 11 10:21:40 2018	DEPLOYED	dispatch-0.1.13     	default  
ingress    	2       	Fri May 11 10:19:32 2018	DEPLOYED	nginx-ingress-0.19.0	default  
openfaas   	1       	Fri May 11 10:21:22 2018	DEPLOYED	openfaas-1.0.0      	default  
postgres   	1       	Fri May 11 10:19:37 2018	DEPLOYED	postgresql-0.8.5    	default  
transport  	1       	Fri May 11 10:21:36 2018	DEPLOYED	kafka-0.0.1         	dispatch
```

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [x] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Fixed by #438
