### ISSUE TITLE
Dispatch does not work with artifactory image registry

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#431]
## Bug Report
When the image registry is configured to point to an artifactory image registry, functions cannot be created.

```
time="2018-05-11T10:51:45Z" level=error msg="Driver error when creating a FaaS function: Error building image for function 'e8aa7160-11b2-449a-ab81-5a93a3d5ab9b': failed to pull image 'symphony-docker-local.jfrog.io/docker-local/dispatch-test/b31e30ba-2f9e-43cd-882a-09e086c48c25:latest': Error response from daemon: Get https://symphony-docker-local.jfrog.io/v2/docker-local/dispatch-test/b31e30ba-2f9e-43cd-882a-09e086c48c25/manifests/latest: unknown: Authentication is required"
```

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by rbtcollins** [comment]
This looks like a trivial lack of registry secret provisioning. 

To prepare the namespace:
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-in-the-cluster-that-holds-your-authorization-token

and then for each pod (deployment/job/statefulset):
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by berndtj** [comment]
Thanks, it's not quite that simple :).  We need to propagate this through our install.  Also, the FaaS needs to support image pull secrets (openfaas does).  Lastly, because of changes in this format between k8s 1.8 and 1.9, things don't always "just work".

**Comment by berndtj** [comment]
Should have a patch very soon though
