### ISSUE TITLE
Validate runtime dependencies

### ISSUE THREAD

**Issue by tenczar** [vmware/dispatch#433]
## Feature Request
Validate the runtime dependencies passed in at image creation.

### Detailed Description

As an example, if an invalid pom.xml file is passed as a runtime-dep at image creation time, this does not cause an error. Only when the function is created and the required dependencies are not present does the user receive an error. It can be hard to track this back to an invalid dependency file.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by rjew** [comment]
Fixed here:
https://github.com/dispatchframework/java-base-image/pull/17
https://github.com/dispatchframework/clojure-base-image/pull/8
https://github.com/dispatchframework/nodejs-base-image/pull/13
https://github.com/dispatchframework/python3-base-image/pull/14
https://github.com/dispatchframework/powershell-base-image/pull/12
