### ISSUE TITLE
Dispatch does not support private registries

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#435]
## Bug Report
While dispatch works to push images to registries which require authentication, it does not support pulling images from private repositories.

### Expected behavior

When configuring a repository, dispatch should propagate the necessary secrets to any entity which requires image pull access.

### Current behavior

Functions cannot be deployed.

### Steps to reproduce

Use a private repo.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [x] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Isn't that fixed by #438 ?

**Comment by berndtj** [comment]
Yes, this is fixed.
