### ISSUE TITLE
Extend login CLI for service accounts

### ISSUE THREAD

**Issue by neosab** [vmware/dispatch#437]
## Feature Request
`dispatch login` command only works for OIDC users and not for service accounts. 

### Detailed Description

`dispatch login` command only works for OIDC users and not for service accounts. When using service accounts, you will always need to specify the `--service-account` & `--jwt-private-key` flags when issuing any CLI commands. You could alternatively use just the `--token` flag but the user needs to know how to generate the signed JWT token for the service account (using other jwt helper tools like jwt-go).

### Possible Implementation

We can improve this by extending the `dispatch login` command to generate a signed JWT token and store it in the ~/.dispatch/config.json file. 

This token will be used when the user issues any CLI command and works as long as the expiration time is valid. After that, the service account user will need to login again using his/her private key.

e.g of the workflow
`dispatch login --service-account test-svc-account --jwt-private-key <path-to-key-file>`

After successful validation,  the svc account user doesn't need to provide any other information.
`dispatch get functions`
`...`

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by zimengyang** [comment]
@neosab Hi Sabari, I will be working on this.

**Comment by zimengyang** [comment]
fixed in #460
