### ISSUE TITLE
Make dispatch create seed-images idempotent

### ISSUE THREAD

**Issue by neosab** [vmware/dispatch#595]
## Feature Request
Make `dispatch create seed-images` idempotent. It will be worthwhile to address #394 first and leverage the functionality for this command.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [X] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by berndtj** [comment]
I would probably leverage the "apply" command.  Also add support for "delete"

**Comment by pzmrzy** [comment]
fix in #785
