### ISSUE TITLE
Support certificates for Dispatch API and API gateway

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#642]
### Detailed Description

All dispatch endpoints should support HTTPs and support customer certificates

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by berndtj** [comment]
@kars7e Is this just documentation?  Can we get that done and close?

**Comment by kars7e** [comment]
There is a way for using an existing certificate, so we just need to add some docs (I added a short description in https://github.com/dispatchframework/chat-ops/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R211, but we should expand on that.) Also is #669 a duplicate?
