### ISSUE TITLE
Documentation for running e2e tests against Dispatch Solo

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#645]
### Expected behavior

Need documentation (may be in Wiki) about how developers can run e2e tests against a Dispatch Solo environment.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by pzmrzy** [comment]
Updated Wiki

**Comment by pzmrzy** [comment]
https://github.com/vmware/dispatch/wiki/Running-E2E-Tests
