### ISSUE TITLE
Existing e2e test suite must pass

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#653]
### Expected behavior

Existing e2e test suite must pass unless failures are expected (event drivers).  Running e2e tests should be easy and well documented.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
Is this done?

**Comment by kars7e** [comment]
It did pass on https://ci.dispatchframework.io/teams/main/pipelines/dispatch-e2e-solo/jobs/test-dispatch-solo/builds/37. There are some recent failures due to clean up PR, this is tracked separately
