### ISSUE TITLE
Assemble PhotonOS based VM

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#654]
### Detailed Description

* VM must include all planned components
* PhotonOS based
* Include solo binary
  - no other dependencies other than docker

The assembly is expected to be manual, as opposed to tools driven (i.e. packer)

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment]
Yes, this is done
