### ISSUE TITLE
Event driver support for Dispatch Solo

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#659]
### Expected behavior

Dispatch Solo should be able to leverage existing event drivers.  This issue only addresses the "pull" type event drivers.  A subsequent issue captures the "expose" feature.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by berndtj** [comment]
https://github.com/vmware/dispatch/pull/695

**Comment by kars7e** [comment]
Looks like this is done
