### ISSUE TITLE
*_mock.go in event-manager

### ISSUE THREAD

**Issue by seanhuxy** [vmware/dispatch#66]
there's some *_mock in event-manager, suggest to move them into a /mock folder, which is did by other managers.

**Comment by kars7e** [comment]
I've removed the "good first issue" label, the reason why _mock files were in the package root directory was circular dependencies that happened when `mock` subdirectory was used. To fix it, a larger refactor is needed to ensure that the interface consumers and implementations don't live in the same package. The refactor done in #244 will fix this issue.

**Comment by kars7e** [comment]
Fixed via #244
