### ISSUE TITLE
Solo OVA must be built via CI/automation

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#663]
### Detailed Description

Building the OVA should be part of CI (concourse) pipeline.  The artifact must be published to a publicly accessible location (Fling).

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by berndtj** [comment]
Should depend on VMC as opposed to physical hardware.

**Comment by kars7e** [comment]
Partially done via #718, the final product will be a release pipeline that pushes OVA to S3.

**Comment by kars7e** [comment]
Fixed in #725
