### ISSUE TITLE
Ensure published OVA has passed all e2e tests

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#664]
### Detailed Description

Before publishing the OVA publicly, the OVA must be run against the full e2e test suite and pass.  This should be fully automated.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment]
Fixed in #725
