### ISSUE TITLE
Auto-generate self signed certs at install/startup

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#667]
### Detailed Description

If the customer does not supply a certificate or domain, the default should be auto-generated self-signed certs.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by zjs** [comment]
Fixed in #680
