### ISSUE TITLE
Support BYO certificates for all Dispatch Solo endpoints

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#669]
### Detailed Description

Customer may configure Dispatch Solo with their own certificates.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment]
Closing as a duplicate of #642
