### ISSUE TITLE
Set password in OVA for ssh access to Dispatch Solo VM

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#670]
### Detailed Description

This should also be used for the bootstrap user to do any further configuration.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by kars7e** [comment]
This is done, you can set the password during OVA deployment in both vSphere and Fusion
