### ISSUE TITLE
Support `dispatch edit <resource> <resource name>`

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#674]
### Detailed Description

Synonymous with `kubectl edit` the command should bring up your $EDITOR and allow you to make changes to an existing resource.  When the editor is saved/closed the resource should be updated.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by berndtj** [comment]
This is done, correct?

**Comment by pzmrzy** [comment]
Yes this is done
