### ISSUE TITLE
Add let's encrypt support to Dispatch

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#702]
## Feature Request

We could automatically obtain certificates for domains that we configure in our API Gateway for Dispatch Solo.

### Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [x] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

**Comment by pzmrzy** [comment]
duplicate #668
