### ISSUE TITLE
Runs are not sorted (by created time)

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#726]
### Expected behavior

Runs should be sorted by created time or (any field).  This makes it hard to figure out which is the relevant run you are looking for.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by zimengyang** [comment]
fixed in #737
