### ISSUE TITLE
Align Dispatch Solo storage locations and OVA disk topology 

### ISSUE THREAD

**Issue by zjs** [vmware/dispatch#728]
### Expected behavior
When using Dispatch Solo, I expect data to be stored in the designated places within the OVA.

### Current behavior
Currently, the OVA mounts partitions under `/storage`, but Dispatch stores data in locations more consistent with the Linux FHS.

### Steps to reproduce
N/A
### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [x] Medium - Issue can be worked around, but is causing pain
   * This may become a blocker if eventual impact on upgrade workflows is considered.
- [ ] High - Blocker

### Possible solution
Option 1: Mount data/log/config partitions in more appropriate locations.

Option 2: Preserve current mount points (perhaps renaming `db` to `data`) and create symlinks from Linux FHS locations to the mounted storage locations.

Option 3: Configure Dispatch to use the current locations under `/storage` (perhaps renaming `db` to `data`, if that's more accurate).

### Your Environment
N/A

**Comment by zimengyang** [comment]
fixed in #750
