### ISSUE TITLE
Solo OVA Login Failure on VMware Workstation 15 Pro

### ISSUE THREAD

**Issue by pzmrzy** [vmware/dispatch#754]
## Bug Report
Solo OVA login failure on VMware Workstation 15 Pro
Same as #747 for Vmware Fusion

### Expected behavior
Solo OVA cannot login with VMware Workstation 15 Pro

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch Solo OVA: v0.0.1
* Vmware Workstation 15 Pro

**Comment by kars7e** [comment]
@pzmrzy Just to clarify, the issue occurs if you shut down and restart the VM right?

**Comment by pzmrzy** [comment]
No, just cannot login to the system, always get login incorrect

**Comment by kars7e** [comment]
tested  solo v0.0.4 OVA with workstation 15.0.2, works ok. Closing
