### ISSUE TITLE
Subscription doesn't valid function

### ISSUE THREAD

**Issue by pzmrzy** [vmware/dispatch#760]
## Bug Report
When create a subscription with a function doesn't exist, the subscription is still ready
![image](https://user-images.githubusercontent.com/5475829/49117236-e05a7780-f254-11e8-8bae-516cd0173ff0.png)

### Expected behavior
Dispatch should return error when create a subscription with invalid function.

### Steps to reproduce
1. create eventdrivertype some_event_type
2. create eventdriver by `dispatch create subscription xxx --name test --event-type some_event_type`
3. run `dispatch get subscription`, it will return a subscription with function name `xxx`

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

**Comment by kars7e** [comment]
The subscription itself is ready. Constantly validating if function exists is an overkill. Adding dependency check (don't allow to delete function that has subscription depending on it) makes more sense.

Anyway, this is covered in https://github.com/vmware/dispatch/issues/30
