### ISSUE TITLE
Add release pipeline

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#79]
When new tag matching a filter is pushed, a release pipeline should be triggered. Pipeline should:
* push docker images with appropriate tags
* push charts with appropriate versions to dispatch charts repo, and update the index
* push CLIs to the S3 bucket
* update README to point to the latest release
* post to slack with the announcement

**Comment by berndtj** [comment]
Fixed cbd8624992d913113843fa21d4f791a3bc16ac78
