### ISSUE TITLE
Dispatch Knative Helm Install Error

### ISSUE THREAD

**Issue by james65535** [vmware/dispatch#793]
### Additional Information
- [ ] Dispatch Solo OVA
- [ ] Dispatch Solo (solo branch)
- [x] Dispatch Knative (master branch)

### Expected behavior
When following Dispatch install instructions, expect the successful return of the following command:
helm upgrade -i --debug ${RELEASE_NAME} ./charts/dispatch --namespace ${DISPATCH_NAMESPACE} -f values.yaml

### Current behavior
helm upgrade command errors with the following output: 
Error: found in requirements.yaml, but missing in charts/ directory: nginx-ingress, minio, docker-registry

### Steps to reproduce
When charts/dispatch has no charts folder for dependencies, the error should generate.  To resolve, fetch the required charts and place them in a folder call charts within the dispatch charts folder.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [X] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Possible solution
Work around: fetch the required charts into charts/dispatch/charts folder.

### Your Environment

* Dispatch CLI version (or git commit): n/a
* Dispatch Chart version (or image[s] tag): dispatch-0.0.0
* Operating System and version: osx mojave
* Kubernetes version (and distribution): 1.11
* Etc (any other useful environmental information):
Helm version: 2.11.0

**Comment by tompscanlan** [comment]
Before running the `helm upgrade`, run 
```bash
helm dependency build ./charts/dispatch/
```

**Comment by tompscanlan** [comment]
pr that would fix this is #796

**Comment by kars7e** [comment]
Fixed in #796, thanks Tom!
