### ISSUE TITLE
Dispatch install always puts port 443 in CLI config

### ISSUE THREAD

**Issue by kars7e** [vmware/dispatch#82]
After installation is complete, dispatch puts port `443` in `.dispatch/config.json`, regardless of the fact how ingress is installed (whether LoadBalancer or NodePort is used). Since dispatch takes care of ingress installation, it should detect and use correct port when ingress is installed with non-standard port.

**Comment by neosab** [comment]
Sounds right. We also need to fix oauth2proxy's redirect_uri [1] to include this port. Otherwise, redirects from IDP will be issued to the standard 443 port. 

[1] https://github.com/vmware/dispatch/blob/master/charts/dispatch/charts/oauth2-proxy/templates/configmap.yaml#L35
