### ISSUE TITLE
Add "application" or similar construct to Dispatch

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#90]
Functions, images, APIs, etc. should be groupable.  We need a new grouping construct "application" (though could use different name as well).  This will have a large impact to just about all services.

- [ ] Bug
- [x] Feature
- [ ] Enhancement

## Detailed Description

In order to support multiple serverless applications or deployments on a single dispatch installation, a grouping construct is required.  Additionally, this construct will be used for authorization and permissions in the future.  Similar to a namespace in k8s, "applications" can be created and managed, then resources get assigned to them.

## Context

This is vital towards making dispatch usable in a production environment

## Complexity

- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [x] High - Significant architectural change or large refactor

## Impact

- [ ] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [x] High - Blocker

## Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by seanhuxy** [comment]
as discussed with @berndtj I am going to work on this feature. Will have a detailed refactor proposal within several days

**Comment by berndtj** [comment]
Split into another issue to capture remaining work

**Comment by seanhuxy** [comment]
first task: add application manager, provide basic functionality of an dispatch application, addressed in https://github.com/vmware/dispatch/pull/143

the remaining work is moved to another issue https://github.com/vmware/dispatch/issues/158
