### ISSUE TITLE
Add update functionality for secrets to dispatch cli.

### ISSUE THREAD

**Issue by tenczar** [vmware/dispatch#92]
- [ ] Enhancement

## Detailed Description
The dispatch cli currently supports create, read and delete functionality on secrets. It needs to support update operations as well.

## Possible Implementation
The only modifiable portion of the secret is the secrets map itself. The name is the key and cannot be modified. Implementation note: The update method will completely rewrite the secrets map. It will not attempt to merge the secrets. If this functionality is desired we can potentially add a flag to support this, but that can be tracked separately.

## Complexity
- [ ] Low - Simple enhancement or bug fix, no architectural changes or refactoring

## Impact
- [ ] Medium - Issue can be worked around, but is causing pain

This issue is related to issue #33

**Comment by berndtj** [comment]
This is done, correct? @tenczar

**Comment by tenczar** [comment]
This was implemented and pushed via PR #105
